Fix/misc shlvl
migferna42/minishell pull request #9
Opened 2020-12-23 19:55 UTC by migferna42

2020-12-24 07:55 UTC, vdedios reviewed
Tiene muy buena pinta pero al haber mergeado la otra rama hay algunos conflictos. Échale un ojo!!

2020-12-24 07:58 UTC, vdedios requested changes
Hay conflictos....

[sad](https://giphy.com/gifs/TU76e2JHkPchG/html5)

2020-12-24 10:41 UTC, migferna42 commented
Se han resueltos los conflictos, y posteriormente se ha resulto un fix, listo para hacer merge

2020-12-25 11:25 UTC, vdedios approved these changes

2020-12-25 11:26 UTC, vdedios commented
![good](https://media.giphy.com/media/0iq4DrlIgRY3RqkwIg/source.gif)

2020-12-25 11:27 UTC, merged